name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: Aymon00/my-app-image
        token: ${{ secrets.TOKEN }}  # استخدام التوكن

        script: |
          sudo yum update -y
