name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: Aymon00/my-app-image
        token: ${{ secrets.TOKEN }}  # استخدام التوكن

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # تأكد من تغيير المنطقة حسب موقع EC2 الخاص بك

    - name: SSH to EC2 and update system
      uses: appleboy/ssh-action@v3
      with:
        host: ${{ secrets.EC2_HOST }}                # عنوان EC2
        username: ${{ secrets.EC2_USER }}            # اسم المستخدم لـ EC2
        password: ${{ secrets.EC2_PASSWORD }}         # كلمة المرور الخاصة بـ EC2
        script: |
          sudo yum update -y
