name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH to EC2 and update system
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.EC2_HOST }}                # عنوان EC2
        username: ${{ secrets.EC2_USER }}            # اسم المستخدم لـ EC2
        password: ${{ secrets.EC2_PASSWORD }}         # كلمة المرور الخاصة بـ EC2
        script: |
          sudo yum update -y
